services:
  postgres-db:
    image: postgres:15.3
    container_name: shopping-cart-postgres-dotnet
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shopping-cart-db-dotnet
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: